language: java
jdk:
  - oraclejdk8

sudo: false
env:
  - TERM=dumb

before_install:
  - chmod +x gradlew

install:
  - ./gradlew assemble

script:
  - ./gradlew check

after_success:
  - ./gradlew jacocoTestReport coveralls

